name: ttgo_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.1.0  # Ajoute cette ligne

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  fluttertoast: ^8.2.1
  firebase_core: ^2.14.0  # Assurez-vous que vous avez cette version ou une version compatible
  firebase_auth: ^4.0.0  #
  cloud_firestore: ^4.0.0
  cupertino_icons: ^1.0.8
  flutter_lints: ^4.0.0
  fl_chart: ^0.40.0
  charts_flutter: ^0.12.0
  firebase_auth_platform_interface: ^7.3.0
  flutter_launcher_icons: ^0.9.2


flutter:
  uses-material-design: true


  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logoC.png"
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
